version: "3.7"
services:
  php:
    build:
      context: .
      args:
        - ENV=dev
    image: phpstorm-xdebug-docker
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    entrypoint: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/public"]
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default

networks:
  default: ~
