version: "3.7"
services:
  php:
    build:
      context: .
      args:
        - ENV=dev
    image: phpstorm-xdebug-docker
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1 #docker network ip.
      PHP_IDE_CONFIG: "serverName=xdebug-docker" #phpstorm variavel de ambiente com o nome do server configurado.
    ports:
      - 8080:80
    entrypoint: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/public"]
